import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      firstname: 'Driss',
      lastname: 'Kanouni',
      email: 'canon78500@hotmail.fr',
      password: bcrypt.hashSync('admin'),
      adminPrivilege: true,
      address: '21 Rue des Abysses, 78500, Sartrouville',
      phoneNumber: '0638918383',
    },
    {
      firstname: 'Zicco',
      lastname: 'McBernick',
      email: 'ziccoBiscotto@hotmail.fr',
      password: bcrypt.hashSync('123456'),
      adminPrivilege: false,
      address: '21 Rue des Abysses, 72000, Bourges',
      phoneNumber: '0638918384',
    },
  ],
  products: [
    {
      name: 'Nike Slim maillot',
      slug: 'nike-slim-maillot',
      category: 'Maillot',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        'high quality maillot Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Adidas Fit maillot',
      slug: 'adidas-fit-maillot',
      category: 'Maillot',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Nike Slim pantalon',
      slug: 'nike-slim-pantalon',
      category: 'Pantalon',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Adidas Fit pantalon',
      slug: 'adidas-fit-pantalon',
      category: 'Pantalon',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    //Ajout à partir d'ici
    //Pantalon
    {
      name: 'Adidas cyan pantalon',
      slug: 'adidas-cyan-pantalon',
      category: 'Pantalon',
      image: '/images/p5.jpg',
      price: 60,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 12,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Adidas Yellow pantalon',
      slug: 'adidas-yellow-pantalon',
      category: 'Pantalon',
      image: '/images/p6.jpg',
      price: 45,
      countInStock: 20,
      brand: 'Adidas',
      rating: 3.0,
      numReviews: 10,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Umbro Grey pantalon',
      slug: 'umbro-grey-pantalon',
      category: 'Pantalon',
      image: '/images/p11.jpg',
      price: 35,
      countInStock: 25,
      brand: 'Umbro',
      rating: 2.0,
      numReviews: 10,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Umbro Blue pantalon',
      slug: 'umbro-blue-pantalon',
      category: 'Pantalon',
      image: '/images/p12.jpg',
      price: 55,
      countInStock: 10,
      brand: 'Umbro',
      rating: 4.0,
      numReviews: 10,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    //Maillot
    {
      name: 'Nike Blue Maillot',
      slug: 'nike-blue-maillot',
      category: 'Maillot',
      image: '/images/p7.jpg',
      price: 30,
      countInStock: 5,
      brand: 'Nike',
      rating: 5.0,
      numReviews: 15,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Adidas Black Maillot',
      slug: 'adidas-black-Maillot',
      category: 'Maillot',
      image: '/images/p8.jpg',
      price: 40,
      countInStock: 15,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 13,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Adidas White Maillot',
      slug: 'adidas-white-maillot',
      category: 'Maillot',
      image: '/images/p9.jpg',
      price: 60,
      countInStock: 14,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Umbro Black Maillot',
      slug: 'umbro-black-maillot',
      category: 'Maillot',
      image: '/images/p10.jpg',
      price: 30,
      countInStock: 8,
      brand: 'Umbro',
      rating: 4.0,
      numReviews: 12,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    //Chaussette
    {
      name: 'Lacoste Green socket',
      slug: 'lacoste-green-socket',
      category: 'Socket',
      image: '/images/p13.jpg',
      price: 15,
      countInStock: 5,
      brand: 'Lacoste',
      rating: 5.0,
      numReviews: 10,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Nike White socket',
      slug: 'nike-white-socket',
      category: 'Socket',
      image: '/images/p14.jpg',
      price: 10,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Sonic Design socket',
      slug: 'Sonic-design-socket',
      category: 'Socket',
      image: '/images/p15.jpg',
      price: 8,
      countInStock: 9,
      brand: 'Sonic',
      rating: 5.0,
      numReviews: 10,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
      name: 'Adidas Green socket',
      slug: 'Adidas-green-socket',
      category: 'Socket',
      image: '/images/p16.jpg',
      price: 13,
      countInStock: 15,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description:
        'high quality product Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam magna mauris, lobortis non pellentesque nec, finibus et neque. Pellentesque molestie non sem non posuere. Aliquam dapibus dui placerat mauris molestie auctor. Quisque nec erat non metus iaculis pulvinar. Vestibulum at orci ligula. Phasellus at aliquam tellus. Suspendisse sit amet nulla lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
  ],
};
export default data;
